name: ci

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,just
      - uses: Swatinem/rust-cache@v2
      - run: just ci
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - run: cargo audit --deny warnings || echo "::warning::cargo audit advisories found" 
